version: '3.8'
services:
  usuario-service:
    build: ./usuario-service
    ports:
      - "8081:8080"
    depends_on:
      - usuario-db
      - rabbitmq

  usuario-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: usuario
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  sala-service:
    build: ./sala-service
    ports:
      - "8082:8080"
    depends_on:
      - sala-db
      - rabbitmq

  sala-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: sala
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"

  reserva-service:
    build: ./reserva-service
    ports:
      - "8083:8080"
    depends_on:
      - reserva-db
      - rabbitmq

  reserva-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: reserva
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
